### ISSUE TITLE
Getting message Operation timed out (Connection timed out) every time I launch test from terminal.

### ISSUE THREAD

**Issue by jacorgaz** [AppiumTestDistribution/AppiumTestDistribution#376]
Hi,

When I try to run the test as a suite from command line (Latest Mojave beta version)

Platform="android" mvn clean -Dtest Runner test

I´m getting the below error:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.URL.openStream(URL.java:1045)
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1547)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
	at com.appium.manager.RemoteAppiumManager.getDevices(RemoteAppiumManager.java:93)
	at com.appium.utils.HostMachineDeviceManager.getDevices(HostMachineDeviceManager.java:133)
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:54)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
java.lang.NullPointerException
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:71)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 76.213 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 76 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.appium.manager.ArtifactsUploader.initializeArtifacts(ArtifactsUploader.java:44)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:39)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:13)

Results :

Failed tests: 
  Runner.testRunner:13 » NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:19 min
[INFO] Finished at: 2018-09-08T12:09:10+02:00
[INFO] Final Memory: 26M/324M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project PagePatternAppium: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/javiercorroto/Documents/Appium/PortalOnce/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

POM:
<dependency>
            <groupId>com.github.saikrishna321</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>ef39d1cdd0</version>
        </dependency>
Capabilities:
{
  "android": {
    "platformName": "android",
    "platformVersion": "8.0.0",
    "app": "./build/wordpress.apk",
    "appPackage": "org.wordpress.android",
    "appActivity": "org.wordpress.android.ui.WPLaunchActivity",
    "deviceName": "10.3.0.47:16837",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.3"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.3"
        }
      ]
    },
    {
      "machineIP": "10.234.1.91",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.2"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.2"
        }
      ]
    }
  ],
  "ATDServiceHost":"127.0.0.1",
  "ATDServicePort":"3000"
}

Thank you in advance

**Comment by saikrishna321** [comment]
@jacorgaz is your RemoteAppiumManager.jar running in your remote machine?

**Comment by jacorgaz** [comment]
@saikrishna321 I believe it is not, could you provide some info about where to download the RemoteAppiumManager.jar? Thank you

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/wiki/Remote-Execution

**Comment by jacorgaz** [comment]
@saikrishna321 It seems to be working but now I´m getting the following error:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
OUTPUT DIRECTORY :/Users/javiercorroto/Documents/Appium/MyProject/target
     _  _       _          _  _             _         
  __| |(_) ___ | |_  _ __ (_)| |__   _   _ | |_   ___ 
 / _` || |/ __|| __|| '__|| || '_ \ | | | || __| / _ \
| (_| || |\__ \| |_ | |   | || |_) || |_| || |_ |  __/
 \__,_||_||___/ \__||_|   |_||_.__/  \__,_| \__| \___|
                                                      

***************************************************

Total Number of devices detected::1

***************************************************

starting running tests in threads
creating directory: Logs
sep 10, 2018 6:39:50 PM com.appium.manager.DeviceAllocationManager getDevices
INFORMACIÓN: All devices connected
creating directory: ADBLogs
...
... TestNG 6.11 by Cédric Beust (cedric@beust.com)
...

**************************************************************************

Starting Appium Server on host 10.3.2.108
**************************************************************************

Picking Default Path for AppiumServiceBuilder
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONObject.<init>(JSONObject.java:214)
	at org.json.JSONObject.<init>(JSONObject.java:357)
	at com.appium.manager.RemoteAppiumManager.startAppiumServer(RemoteAppiumManager.java:75)
	at com.appium.manager.AppiumServerManager.startAppiumServerSingleSession(AppiumServerManager.java:38)
	at com.appium.manager.AppiumServerManager.startAppiumServer(AppiumServerManager.java:56)
	at com.appium.manager.AppiumParallelMethodTestListener.onStart(AppiumParallelMethodTestListener.java:178)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:226)
	at org.testng.SuiteRunner.run(SuiteRunner.java:287)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.appium.executor.MyTestExecutor.runMethodParallel(MyTestExecutor.java:174)
	at com.appium.executor.MyTestExecutor.runMethodParallelAppium(MyTestExecutor.java:148)
	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:140)
	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:90)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:82)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:86)
	at com.appium.tests.Runner.testRunner(Runner.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
23
sep 10, 2018 6:39:51 PM com.appium.manager.DeviceAllocationManager allocateDevice
INFORMACIÓN: Allocated Device com.appium.utils.AppiumDevice@6e0f6b33 for Execution
sep 10, 2018 6:39:51 PM com.appium.manager.AppiumDriverManager startAppiumDriverInstance
INFORMACIÓN: Caps generated---Capabilities {app: /Users/javiercorroto/Docume..., appActivity: org.wordpress.android.ui.WP..., appPackage: org.wordpress.android, automationName: UIAutomator2, deviceName: 10.3.0.43:15569, noSign: true, platformName: android, platformVersion: 7.0, systemPort: 55223, udid: 10.3.0.43:15569}null
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONObject.<init>(JSONObject.java:214)
	at org.json.JSONObject.<init>(JSONObject.java:357)
	at com.appium.manager.RemoteAppiumManager.getRemoteWDHubIP(RemoteAppiumManager.java:34)
	at com.appium.manager.AppiumDriverManager.getRemoteWDHubIP(AppiumDriverManager.java:74)
	at com.appium.manager.AppiumDriverManager.getMobileAndroidElementAppiumDriver(AppiumDriverManager.java:47)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:92)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:110)
	at com.appium.manager.AppiumParallelMethodTestListener.onTestStart(AppiumParallelMethodTestListener.java:121)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1739)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:640)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
scrollOverReader execution failed in count: 0

java.lang.NullPointerException
	at com.appium.utils.ScreenShotManager.captureScreenShot(ScreenShotManager.java:75)
	at com.appium.manager.TestLogger.handleTestFailure(TestLogger.java:196)
	at com.appium.manager.TestLogger.endLog(TestLogger.java:98)
	at com.appium.manager.ReportManager.endLogTestResults(ReportManager.java:42)
	at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:94)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:566)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:713)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)


json capabilities seems to be ok:

{
  "android": {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "./build/wordpress.apk",
    "appPackage": "org.wordpress.android",
    "appActivity": "org.wordpress.android.ui.WPLaunchActivity",
    "deviceName": "10.3.0.43:15569",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "10.3.2.108",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.3"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.3"
        }
      ]
    },
    {
      "machineIP": "10.3.2.108",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.2"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.2"
        }
      ]
    }
  ],
  "ATDServiceHost":"127.0.0.1",
  "ATDServicePort":"3000"
}

Should I open another issue?

Thanks for your your help :)

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/issues/343

**Comment by jacorgaz** [comment]
@saikrishna321 I had a look at the json as mentioned on #343 but i´m still getting the same error.

I just modify the machineIP and deviceName parameter in the json 
[capabilities.txt](https://github.com/saikrishna321/AppiumTestDistribution/files/2367653/capabilities.txt)

**Comment by saikrishna321** [comment]
Which version r u using ?1

**Comment by jacorgaz** [comment]
Ef39d1cdd0, should I change?

**Comment by saikrishna321** [comment]
@jacorgaz your version looks fine. Try with below json

```
{
  "android": {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "./build/wordpress.apk",
    "appPackage": "org.wordpress.android",
    "appActivity": "org.wordpress.android.ui.WPLaunchActivity",
    "deviceName": "10.3.0.43:15569",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "10.3.2.108",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.3"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.3"
        },
        {
          "deviceName": "iPhone 6",
          "OS": "11.2"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.2"
        }
      ]
    }
  ],
  "ATDServiceHost":"127.0.0.1",
  "ATDServicePort":"3000"
}
```
Refer sample:
https://github.com/saikrishna321/PageObjectPatternAppium

**Comment by jacorgaz** [comment]
@saikrishna321 Still not luck. I have tried on my colleagues computer and it works. Everything is similar between the two machines except JDK version install. I´m starting to think is because I recently updated to Mojave, it should not be a problem. I´m gonna download the code into another mac machine with High Sierra and see if it works. I really appreciate your help on this matter. If you come along any other idea to fix it it´d be welcomed :)

**Comment by saikrishna321** [comment]
@jacorgaz which version of JDK you have ?

**Comment by jacorgaz** [comment]
@saikrishna321  JDK 1.8.0_181, org.apache.maven.plugins 2.18.1, maven-compiler-plugin 1.8. Mojave latest beta.

**Comment by jacorgaz** [comment]
I'm using intellij id community version, latest versionn

**Comment by saikrishna321** [comment]
@jacorgaz that should work.

**Comment by orvilia** [comment]
@saikrishna321 @jacorgaz Any Luck on this issue....I am still getting this error. Please help

**Comment by orvilia** [comment]
@saikrishna321 
I am using JDK1.8 and appium 1.9.0, maven 3.3.9. 

Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@2fc14f68
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.URL.openStream(URL.java:1045)
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1547)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
	at com.appium.manager.RemoteAppiumManager.getDevices(RemoteAppiumManager.java:93)
	at com.appium.utils.HostMachineDeviceManager.getDevices(HostMachineDeviceManager.java:133)
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:54)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.bjs.test.Runner.testApp(Runner.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:589)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
	at org.testng.SuiteRunner.run(SuiteRunner.java:302)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
java.lang.NullPointerException
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:71)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.bjs.test.Runner.testApp(Runner.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:589)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
	at org.testng.SuiteRunner.run(SuiteRunner.java:302)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 96.026 sec <<< FAILURE!
testApp(com.bjs.test.Runner)  Time elapsed: 95.174 sec  <<< FAILURE!
java.lang.NullPointerException
	at com.appium.manager.ArtifactsUploader.initializeArtifacts(ArtifactsUploader.java:44)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:39)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.bjs.test.Runner.testApp(Runner.java:14)


Results :

Failed tests:   testApp(com.bjs.test.Runner)

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by saikrishna321** [comment]
@orvilia can you share your caps.json ? 

```
{
  "android": {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "./build/wordpress.apk",
    "appPackage": "org.wordpress.android",
    "appActivity": "org.wordpress.android.ui.WPLaunchActivity",
    "deviceName": "10.3.0.43:15569",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
// 127.0.0.1 if your running on localmachine if you want to run the tests on remote machines you need to give remote machine IP and start server as in the link https://github.com/saikrishna321/AppiumTestDistribution/wiki/Remote-Execution
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.3"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.3"
        },
        {
          "deviceName": "iPhone 6",
          "OS": "11.2"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.2"
        }
      ]
    }
  ]
}
```

**Comment by saikrishna321** [comment]
can u pls a new issue for this .. this is bug

**Comment by orvilia** [comment]
@saikrishna321 Hey Buddy.....We fixed the issue...I would say its not a bug. We corrected the capabilities.json and it worked....Great work guys....

**Comment by saikrishna321** [comment]
can u post the corrected caps.json pls

**Comment by orvilia** [comment]
@saikrishna321 Sure....Please find below 

<-------JSON----->>>>

{
  "android": {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "/Users/saurabhdubey/com.bjs.autoapp/src/test/java/ApiDemos-debug.apk",
    "appPackage": "io.appium.android.apis",
    "deviceName": "android",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.4"
        }
      ]
    }
  ],

  "ATDServiceHost":"127.0.0.1",
  "ATDServicePort":"3000"

}

**Comment by saikrishna321** [comment]
@orvilia Thanks 👍 

R u running both android and iOS or only Android ?

**Comment by jacorgaz** [comment]
@saikrishna321 Sorry for answering with such a delay. It´s working with Android but if launching with iOS with @orvilia capabilities and with the one you provides the error  **JSONObject text must begin with '{' at 0 [character 1 line 1]** still persists. @orvilia do you have the same problem?

**Comment by saikrishna321** [comment]
@jacorgaz can you please post your caps.json and also the ATD version

**Comment by jacorgaz** [comment]
@saikrishna321 <version>ef39d1cdd0</version> 

<-------JSON----->>>>
{
  "android": {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "/Users/javiercorroto/Documents/Appium/ONCE/build/wordpress.apk",
    "appPackage": "org.wordpress.android",
    "deviceName": "android",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "[My machine ip]",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "12.0"
        }
      ]
    }
  ],

  "ATDServiceHost":"127.0.0.1",
  "ATDServicePort":"3000"
}

**Comment by saikrishna321** [comment]
@jacorgaz try with latest master '690ed1b'

>> [My machine ip] --> is this your IP address or 127.0.0.1 ?

**Comment by jacorgaz** [comment]
@saikrishna321 with '690ed1b'  i´m now getting **java.lang.IllegalArgumentException: Please set automationName as UIAutomator2 or Espresso to create Android driver** and for iOS **org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]**

I´m going to describe all the steps done:

1. Follow prerequisites https://github.com/saikrishna321/AppiumTestDistribution/wiki/Prerequisites
2. Clon https://github.com/saikrishna321/PageObjectPatternAppium.git
3. Add 690ed1b in pom.xml
4. Add capabilities as in my latest comment with my machine ip and 127.0.0.1

Am I missing something?

Thank you for all your help all this time

**Comment by saikrishna321** [comment]
you need to add automationName as UIAutomator2 in caps.json for android. 

Can you please post complete exception pls ?
